// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include <libobe/model-odb.hxx>

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/view-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>
#include <odb/pgsql/view-result.hxx>

namespace odb
{
  // file_record
  //

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  persist_statement_name[] = "persist_obe_file_record";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  find_statement_name[] = "find_obe_file_record";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  update_statement_name[] = "update_obe_file_record";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  erase_statement_name[] = "erase_obe_file_record";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  query_statement_name[] = "query_obe_file_record";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::
  erase_query_statement_name[] = "erase_query_obe_file_record";

  const unsigned int access::object_traits_impl< ::obe::file_record, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int4_oid,
    pgsql::bytea_oid
  };

  const unsigned int access::object_traits_impl< ::obe::file_record, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::obe::file_record, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int4_oid,
    pgsql::bytea_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::obe::file_record, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::obe::file_record, id_pgsql >::id_type
  access::object_traits_impl< ::obe::file_record, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.id_value,
        i.id_null);

      // From model.hxx:60:12
      id = obe::file_id 
      {
         (vt) 
      };
    }

    return id;
  }

  access::object_traits_impl< ::obe::file_record, id_pgsql >::id_type
  access::object_traits_impl< ::obe::file_record, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.id_value,
        i.id_null);

      // From model.hxx:60:12
      id = obe::file_id 
      {
         (vt) 
      };
    }

    return id;
  }

  bool access::object_traits_impl< ::obe::file_record, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // title
    //
    t[1UL] = 0;

    // owner
    //
    t[2UL] = 0;

    // name
    //
    if (t[3UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // flag1
    //
    t[4UL] = 0;

    // flag2
    //
    t[5UL] = 0;

    // created
    //
    t[6UL] = 0;

    // modified
    //
    t[7UL] = 0;

    // size
    //
    t[8UL] = 0;

    // data
    //
    if (t[9UL])
    {
      i.data_value.capacity (i.data_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // title
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.title_value;
    b[n].is_null = &i.title_null;
    n++;

    // owner
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.owner_value;
    b[n].is_null = &i.owner_null;
    n++;

    // name
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.name_value.data_ptr ();
    b[n].capacity = i.name_value.capacity ();
    b[n].size = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // flag1
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.flag1_value;
    b[n].is_null = &i.flag1_null;
    n++;

    // flag2
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.flag2_value;
    b[n].is_null = &i.flag2_null;
    n++;

    // created
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.created_value;
    b[n].is_null = &i.created_null;
    n++;

    // modified
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.modified_value;
    b[n].is_null = &i.modified_null;
    n++;

    // size
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.size_value;
    b[n].is_null = &i.size_null;
    n++;

    // data
    //
    b[n].type = pgsql::bind::bytea;
    b[n].buffer = i.data_value.data_ptr ();
    b[n].capacity = i.data_value.capacity ();
    b[n].size = &i.data_size;
    b[n].is_null = &i.data_null;
    n++;
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::obe::file_record, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // title
    //
    {
      ::obe::title_id const& v =
        o.title;

      bool is_null (false);

      // From model.hxx:50:12
      ::uint32_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_image (
        i.title_value, is_null, vt);
      i.title_null = is_null;
    }

    // owner
    //
    {
      ::obe::user_id const& v =
        o.owner;

      bool is_null (false);

      // From model.hxx:55:12
      ::uint64_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_image (
        i.owner_value, is_null, vt);
      i.owner_null = is_null;
    }

    // name
    //
    {
      ::std::string const& v =
        o.name;

      bool is_null (false);

      std::size_t size (0);
      std::size_t cap (i.name_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.name_value,
        size,
        is_null,
        v);
      i.name_null = is_null;
      i.name_size = size;
      grew = grew || (cap != i.name_value.capacity ());
    }

    // flag1
    //
    {
      bool const& v =
        o.flag1;

      bool is_null (false);

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.flag1_value, is_null, v);
      i.flag1_null = is_null;
    }

    // flag2
    //
    {
      bool const& v =
        o.flag2;

      bool is_null (false);

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.flag2_value, is_null, v);
      i.flag2_null = is_null;
    }

    // created
    //
    {
      ::obe::timestamp const& v =
        o.created;

      bool is_null (false);

      // From model.hxx:68:12
      ::int64_t const& vt =
        std::chrono::duration_cast < std::chrono::nanoseconds > ((v).time_since_epoch ()).count ();

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.created_value, is_null, vt);
      i.created_null = is_null;
    }

    // modified
    //
    {
      ::obe::timestamp const& v =
        o.modified;

      bool is_null (false);

      // From model.hxx:68:12
      ::int64_t const& vt =
        std::chrono::duration_cast < std::chrono::nanoseconds > ((v).time_since_epoch ()).count ();

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.modified_value, is_null, vt);
      i.modified_null = is_null;
    }

    // size
    //
    {
      ::uint32_t const& v =
        o.size;

      bool is_null (false);

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_image (
        i.size_value, is_null, v);
      i.size_null = is_null;
    }

    // data
    //
    {
      ::obe::bytes const& v =
        o.data;

      bool is_null (false);

      std::size_t size (0);
      std::size_t cap (i.data_value.capacity ());
      pgsql::value_traits<
          ::obe::bytes,
          pgsql::id_bytea >::set_image (
        i.data_value,
        size,
        is_null,
        v);
      i.data_null = is_null;
      i.data_size = size;
      grew = grew || (cap != i.data_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::obe::file_id& v =
        o.id;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.id_value,
        i.id_null);

      // From model.hxx:60:12
      v = obe::file_id 
      {
         (vt) 
      };
    }

    // title
    //
    {
      ::obe::title_id& v =
        o.title;

      ::uint32_t vt;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        vt,
        i.title_value,
        i.title_null);

      // From model.hxx:50:12
      v = obe::title_id 
      {
         (vt) 
      };
    }

    // owner
    //
    {
      ::obe::user_id& v =
        o.owner;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.owner_value,
        i.owner_null);

      // From model.hxx:55:12
      v = obe::user_id 
      {
         (vt) 
      };
    }

    // name
    //
    {
      ::std::string& v =
        o.name;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // flag1
    //
    {
      bool& v =
        o.flag1;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.flag1_value,
        i.flag1_null);
    }

    // flag2
    //
    {
      bool& v =
        o.flag2;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.flag2_value,
        i.flag2_null);
    }

    // created
    //
    {
      ::obe::timestamp& v =
        o.created;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.created_value,
        i.created_null);

      // From model.hxx:68:12
      v = obe::timestamp (std::chrono::duration_cast < obe::duration > (std::chrono::nanoseconds (vt)));
    }

    // modified
    //
    {
      ::obe::timestamp& v =
        o.modified;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.modified_value,
        i.modified_null);

      // From model.hxx:68:12
      v = obe::timestamp (std::chrono::duration_cast < obe::duration > (std::chrono::nanoseconds (vt)));
    }

    // size
    //
    {
      ::uint32_t& v =
        o.size;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        v,
        i.size_value,
        i.size_null);
    }

    // data
    //
    {
      ::obe::bytes& v =
        o.data;

      pgsql::value_traits<
          ::obe::bytes,
          pgsql::id_bytea >::set_value (
        v,
        i.data_value,
        i.data_size,
        i.data_null);
    }
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);

      // From model.hxx:60:12
      ::uint64_t const& vt =
        std::to_underlying (id);

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, vt);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::persist_statement[] =
  "INSERT INTO \"file\" "
  "(\"id\", "
  "\"title\", "
  "\"owner\", "
  "\"name\", "
  "\"flag1\", "
  "\"flag2\", "
  "\"created\", "
  "\"modified\", "
  "\"size\", "
  "\"data\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::find_statement[] =
  "SELECT "
  "\"file\".\"id\", "
  "\"file\".\"title\", "
  "\"file\".\"owner\", "
  "\"file\".\"name\", "
  "\"file\".\"flag1\", "
  "\"file\".\"flag2\", "
  "\"file\".\"created\", "
  "\"file\".\"modified\", "
  "\"file\".\"size\", "
  "\"file\".\"data\" "
  "FROM \"file\" "
  "WHERE \"file\".\"id\"=$1";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::update_statement[] =
  "UPDATE \"file\" "
  "SET "
  "\"title\"=$1, "
  "\"owner\"=$2, "
  "\"name\"=$3, "
  "\"flag1\"=$4, "
  "\"flag2\"=$5, "
  "\"created\"=$6, "
  "\"modified\"=$7, "
  "\"size\"=$8, "
  "\"data\"=$9 "
  "WHERE \"id\"=$10";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::erase_statement[] =
  "DELETE FROM \"file\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::query_statement[] =
  "SELECT "
  "\"file\".\"id\", "
  "\"file\".\"title\", "
  "\"file\".\"owner\", "
  "\"file\".\"name\", "
  "\"file\".\"flag1\", "
  "\"file\".\"flag2\", "
  "\"file\".\"created\", "
  "\"file\".\"modified\", "
  "\"file\".\"size\", "
  "\"file\".\"data\" "
  "FROM \"file\"";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"file\"";

  const char access::object_traits_impl< ::obe::file_record, id_pgsql >::table_name[] =
  "\"file\"";

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::obe::file_record, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::obe::file_record, id_pgsql >::pointer_type
  access::object_traits_impl< ::obe::file_record, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (nullptr);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::obe::file_record, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::obe::file_record, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::obe::file_record, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::obe::file_record, id_pgsql >::object_type >
  access::object_traits_impl< ::obe::file_record, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::object_result_impl<object_type>> r (
      std::make_shared<pgsql::object_result_impl<object_type>> (
        q, std::move (st), sts, nullptr));

    return result<object_type> (std::move (r));
  }

  unsigned long long access::object_traits_impl< ::obe::file_record, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // file_record_header
  //

  const char access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  query_statement_name[] = "query_obe_file_record_header";

  bool access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // title
    //
    t[1UL] = 0;

    // owner
    //
    t[2UL] = 0;

    // name
    //
    if (t[3UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // flag1
    //
    t[4UL] = 0;

    // flag2
    //
    t[5UL] = 0;

    // created
    //
    t[6UL] = 0;

    // modified
    //
    t[7UL] = 0;

    // size
    //
    t[8UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // id
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    n++;

    // title
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.title_value;
    b[n].is_null = &i.title_null;
    n++;

    // owner
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.owner_value;
    b[n].is_null = &i.owner_null;
    n++;

    // name
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.name_value.data_ptr ();
    b[n].capacity = i.name_value.capacity ();
    b[n].size = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // flag1
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.flag1_value;
    b[n].is_null = &i.flag1_null;
    n++;

    // flag2
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.flag2_value;
    b[n].is_null = &i.flag2_null;
    n++;

    // created
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.created_value;
    b[n].is_null = &i.created_null;
    n++;

    // modified
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.modified_value;
    b[n].is_null = &i.modified_null;
    n++;

    // size
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.size_value;
    b[n].is_null = &i.size_null;
    n++;
  }

  void access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::obe::file_id& v =
        o.id;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.id_value,
        i.id_null);

      // From model.hxx:60:12
      v = obe::file_id 
      {
         (vt) 
      };
    }

    // title
    //
    {
      ::obe::title_id& v =
        o.title;

      ::uint32_t vt;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        vt,
        i.title_value,
        i.title_null);

      // From model.hxx:50:12
      v = obe::title_id 
      {
         (vt) 
      };
    }

    // owner
    //
    {
      ::obe::user_id& v =
        o.owner;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.owner_value,
        i.owner_null);

      // From model.hxx:55:12
      v = obe::user_id 
      {
         (vt) 
      };
    }

    // name
    //
    {
      ::std::string& v =
        o.name;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // flag1
    //
    {
      bool& v =
        o.flag1;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.flag1_value,
        i.flag1_null);
    }

    // flag2
    //
    {
      bool& v =
        o.flag2;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.flag2_value,
        i.flag2_null);
    }

    // created
    //
    {
      ::obe::timestamp& v =
        o.created;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.created_value,
        i.created_null);

      // From model.hxx:68:12
      v = obe::timestamp (std::chrono::duration_cast < obe::duration > (std::chrono::nanoseconds (vt)));
    }

    // modified
    //
    {
      ::obe::timestamp& v =
        o.modified;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.modified_value,
        i.modified_null);

      // From model.hxx:68:12
      v = obe::timestamp (std::chrono::duration_cast < obe::duration > (std::chrono::nanoseconds (vt)));
    }

    // size
    //
    {
      ::uint32_t& v =
        o.size;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        v,
        i.size_value,
        i.size_null);
    }
  }

  access::view_traits_impl< ::obe::file_record_header, id_pgsql >::query_base_type
  access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "\"file\".\"id\", "
      "\"file\".\"title\", "
      "\"file\".\"owner\", "
      "\"file\".\"name\", "
      "\"file\".\"flag1\", "
      "\"file\".\"flag2\", "
      "\"file\".\"created\", "
      "\"file\".\"modified\", "
      "\"file\".\"size\" ");

    r += "FROM \"file\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::obe::file_record_header, id_pgsql >::view_type >
  access::view_traits_impl< ::obe::file_record_header, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::view_result_impl<view_type>> r (
      std::make_shared<pgsql::view_result_impl<view_type>> (
        qs, std::move (st), sts, nullptr));

    return result<view_type> (std::move (r));
  }

  // file_record_count
  //

  const char access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  query_statement_name[] = "query_obe_file_record_count";

  bool access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // result
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // result
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.result_value;
    b[n].is_null = &i.result_null;
    n++;
  }

  void access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // result
    //
    {
      ::uint64_t& v =
        o.result;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.result_value,
        i.result_null);
    }
  }

  access::view_traits_impl< ::obe::file_record_count, id_pgsql >::query_base_type
  access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(\"file\".\"id\") ");

    r += "FROM \"file\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::obe::file_record_count, id_pgsql >::view_type >
  access::view_traits_impl< ::obe::file_record_count, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::view_result_impl<view_type>> r (
      std::make_shared<pgsql::view_result_impl<view_type>> (
        qs, std::move (st), sts, nullptr));

    return result<view_type> (std::move (r));
  }

  // performance_key
  //

  bool access::composite_value_traits< ::obe::performance_key, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // title
    //
    t[0UL] = 0;

    // kind
    //
    t[1UL] = 0;

    // user
    //
    t[2UL] = 0;

    return grew;
  }

  void access::composite_value_traits< ::obe::performance_key, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // title
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.title_value;
    b[n].is_null = &i.title_null;
    n++;

    // kind
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.kind_value;
    b[n].is_null = &i.kind_null;
    n++;

    // user
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.user_value;
    b[n].is_null = &i.user_null;
    n++;
  }

  bool access::composite_value_traits< ::obe::performance_key, id_pgsql >::
  init (image_type& i,
        const value_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // title
    //
    {
      ::obe::title_id const& v =
        o.title;

      bool is_null (false);

      // From model.hxx:50:12
      ::uint32_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_image (
        i.title_value, is_null, vt);
      i.title_null = is_null;
    }

    // kind
    //
    {
      ::uint32_t const& v =
        o.kind;

      bool is_null (false);

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_image (
        i.kind_value, is_null, v);
      i.kind_null = is_null;
    }

    // user
    //
    {
      ::obe::user_id const& v =
        o.user;

      bool is_null (false);

      // From model.hxx:55:12
      ::uint64_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_image (
        i.user_value, is_null, vt);
      i.user_null = is_null;
    }

    return grew;
  }

  void access::composite_value_traits< ::obe::performance_key, id_pgsql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // title
    //
    {
      ::obe::title_id& v =
        o.title;

      ::uint32_t vt;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        vt,
        i.title_value,
        i.title_null);

      // From model.hxx:50:12
      v = obe::title_id 
      {
         (vt) 
      };
    }

    // kind
    //
    {
      ::uint32_t& v =
        o.kind;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        v,
        i.kind_value,
        i.kind_null);
    }

    // user
    //
    {
      ::obe::user_id& v =
        o.user;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.user_value,
        i.user_null);

      // From model.hxx:55:12
      v = obe::user_id 
      {
         (vt) 
      };
    }
  }

  // performance_record
  //

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  persist_statement_name[] = "persist_obe_performance_record";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  find_statement_name[] = "find_obe_performance_record";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  update_statement_name[] = "update_obe_performance_record";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  erase_statement_name[] = "erase_obe_performance_record";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  query_statement_name[] = "query_obe_performance_record";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  erase_query_statement_name[] = "erase_query_obe_performance_record";

  const unsigned int access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::obe::performance_record, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::obe::performance_record, id_pgsql >::id_type
  access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::obe::performance_key, id_pgsql >::init (
        id,
        i.id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    if (composite_value_traits< ::obe::performance_key, id_pgsql >::grow (
          i.id_value, t + 0UL))
      grew = true;

    // value
    //
    t[3UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::obe::performance_key, id_pgsql >::bind (
        b + n, i.id_value, sk);
      n += 3UL;
    }

    // value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.value_value;
    b[n].is_null = &i.value_null;
    n++;
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    pgsql::statement_kind sk (pgsql::statement_select);
    composite_value_traits< ::obe::performance_key, id_pgsql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      ::obe::performance_key const& v =
        o.id;

      composite_value_traits< ::obe::performance_key, id_pgsql >::init (
        i.id_value,
        v,
        sk);
    }

    // value
    //
    {
      ::int64_t const& v =
        o.value;

      bool is_null (false);

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.value_value, is_null, v);
      i.value_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::obe::performance_key& v =
        o.id;

      composite_value_traits< ::obe::performance_key, id_pgsql >::init (
        v,
        i.id_value,
        db);
    }

    // value
    //
    {
      ::int64_t& v =
        o.value;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.value_value,
        i.value_null);
    }
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    pgsql::statement_kind sk (pgsql::statement_select);
    {
      composite_value_traits< ::obe::performance_key, id_pgsql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::persist_statement[] =
  "INSERT INTO \"performance\" "
  "(\"title\", "
  "\"kind\", "
  "\"user\", "
  "\"value\") "
  "VALUES "
  "($1, $2, $3, $4)";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::find_statement[] =
  "SELECT "
  "\"performance\".\"title\", "
  "\"performance\".\"kind\", "
  "\"performance\".\"user\", "
  "\"performance\".\"value\" "
  "FROM \"performance\" "
  "WHERE \"performance\".\"title\"=$1 AND \"performance\".\"kind\"=$2 AND \"performance\".\"user\"=$3";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::update_statement[] =
  "UPDATE \"performance\" "
  "SET "
  "\"value\"=$1 "
  "WHERE \"title\"=$2 AND \"kind\"=$3 AND \"user\"=$4";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::erase_statement[] =
  "DELETE FROM \"performance\" "
  "WHERE \"title\"=$1 AND \"kind\"=$2 AND \"user\"=$3";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::query_statement[] =
  "SELECT "
  "\"performance\".\"title\", "
  "\"performance\".\"kind\", "
  "\"performance\".\"user\", "
  "\"performance\".\"value\" "
  "FROM \"performance\"";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"performance\"";

  const char access::object_traits_impl< ::obe::performance_record, id_pgsql >::table_name[] =
  "\"performance\"";

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::obe::performance_record, id_pgsql >::pointer_type
  access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (nullptr);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::obe::performance_record, id_pgsql >::object_type >
  access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::object_result_impl<object_type>> r (
      std::make_shared<pgsql::object_result_impl<object_type>> (
        q, std::move (st), sts, nullptr));

    return result<object_type> (std::move (r));
  }

  unsigned long long access::object_traits_impl< ::obe::performance_record, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"performance\" CASCADE");
          db.execute ("DROP TABLE IF EXISTS \"file\" CASCADE");
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" BIGINT NOT NULL,\n"
                      "  \"migration\" BOOLEAN NOT NULL)");
          db.execute ("DELETE FROM \"schema_version\"\n"
                      "  WHERE \"name\" = ''");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"file\" (\n"
                      "  \"id\" BIGSERIAL NOT NULL PRIMARY KEY,\n"
                      "  \"title\" INTEGER NOT NULL,\n"
                      "  \"owner\" BIGINT NOT NULL,\n"
                      "  \"name\" TEXT NOT NULL,\n"
                      "  \"flag1\" BOOLEAN NOT NULL,\n"
                      "  \"flag2\" BOOLEAN NOT NULL,\n"
                      "  \"created\" BIGINT NOT NULL,\n"
                      "  \"modified\" BIGINT NOT NULL,\n"
                      "  \"size\" INTEGER NOT NULL,\n"
                      "  \"data\" BYTEA NOT NULL)");
          db.execute ("CREATE UNIQUE INDEX \"file_title_owner_name_i\"\n"
                      "  ON \"file\" (\n"
                      "    \"title\",\n"
                      "    \"owner\",\n"
                      "    \"name\")");
          db.execute ("CREATE TABLE \"performance\" (\n"
                      "  \"title\" INTEGER NOT NULL,\n"
                      "  \"kind\" INTEGER NOT NULL,\n"
                      "  \"user\" BIGINT NOT NULL,\n"
                      "  \"value\" BIGINT NOT NULL,\n"
                      "  PRIMARY KEY (\"title\",\n"
                      "               \"kind\",\n"
                      "               \"user\"))");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" BIGINT NOT NULL,\n"
                      "  \"migration\" BOOLEAN NOT NULL)");
          db.execute ("INSERT INTO \"schema_version\" (\n"
                      "  \"name\", \"version\", \"migration\")\n"
                      "  SELECT '', 1, FALSE\n"
                      "  WHERE NOT EXISTS (\n"
                      "    SELECT 1 FROM \"schema_version\" WHERE \"name\" = '')");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_pgsql,
    "",
    1ULL,
    0);
}

#include <odb/post.hxx>
