// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef LIBOBE_MODEL_ODB_HXX
#define LIBOBE_MODEL_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20600UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include <libobe/model.hxx>

#include <memory>
#include <cstddef>
#include <utility>
#include <type_traits>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/std-optional-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>

namespace odb
{
  // file_record
  //
  template <>
  struct class_traits< ::obe::file_record >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::obe::file_record >
  {
    public:
    typedef ::obe::file_record object_type;
    typedef ::std::unique_ptr< ::obe::file_record > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::obe::file_id id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // file_record_header
  //
  template <>
  struct class_traits< ::obe::file_record_header >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::obe::file_record_header >
  {
    public:
    typedef ::obe::file_record_header view_type;
    typedef ::obe::file_record_header* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // file_record_count
  //
  template <>
  struct class_traits< ::obe::file_record_count >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::obe::file_record_count >
  {
    public:
    typedef ::obe::file_record_count view_type;
    typedef ::obe::file_record_count* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // performance_record
  //
  template <>
  struct class_traits< ::obe::performance_record >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::obe::performance_record >
  {
    public:
    typedef ::obe::performance_record object_type;
    typedef ::std::unique_ptr< ::obe::performance_record > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::obe::performance_key id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // file_record
  //
  template <typename A>
  struct query_columns< ::obe::file_record, id_pgsql, A >
  {
    // id
    //
    struct id_base_type_: pgsql::query_column_base
    {
      using query_column_base::query_column_base;

      static void
      append (pgsql::query_base& q,
              pgsql::val_bind< ::obe::file_id > v,
              const char* conv)
      {
        // From model.hxx:59:12
        ::uint64_t const& vt =
          std::to_underlying (v.val);

        q.append<
          ::uint64_t,
          pgsql::id_bigint > (
            pgsql::val_bind< ::uint64_t > (vt),
            conv);
      }

      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             std::is_reference< decltype (
                 // From model.hxx:59:12
                 std::to_underlying (r.ref)) >::value>::type
      {
        // From model.hxx:59:12
        ::uint64_t const& rt =
          std::to_underlying (r.ref);

        q.append<
          ::uint64_t,
          pgsql::id_bigint > (
            pgsql::ref_bind< ::uint64_t > (rt),
            conv);
      }

      // If a compiler error points to the line below, then it most likely
      // means that the 'to' clause expression of the respective map pragma is
      // not of a reference type and thus binding by reference is not
      // supported for this query member.
      //
      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             !std::is_reference< decltype (
                 // From model.hxx:59:12
                 std::to_underlying (r.ref)) >::value>::type
        = delete;

      static void*
      param_factory () = delete;
    };

    typedef
    pgsql::query_column<
      ::obe::file_id,
      pgsql::id_bigint,
      id_base_type_ >
    id_type_;

    static const id_type_ id;

    // title
    //
    struct title_base_type_: pgsql::query_column_base
    {
      using query_column_base::query_column_base;

      static void
      append (pgsql::query_base& q,
              pgsql::val_bind< ::obe::title_id > v,
              const char* conv)
      {
        // From model.hxx:49:12
        ::uint32_t const& vt =
          std::to_underlying (v.val);

        q.append<
          ::uint32_t,
          pgsql::id_integer > (
            pgsql::val_bind< ::uint32_t > (vt),
            conv);
      }

      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             std::is_reference< decltype (
                 // From model.hxx:49:12
                 std::to_underlying (r.ref)) >::value>::type
      {
        // From model.hxx:49:12
        ::uint32_t const& rt =
          std::to_underlying (r.ref);

        q.append<
          ::uint32_t,
          pgsql::id_integer > (
            pgsql::ref_bind< ::uint32_t > (rt),
            conv);
      }

      // If a compiler error points to the line below, then it most likely
      // means that the 'to' clause expression of the respective map pragma is
      // not of a reference type and thus binding by reference is not
      // supported for this query member.
      //
      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             !std::is_reference< decltype (
                 // From model.hxx:49:12
                 std::to_underlying (r.ref)) >::value>::type
        = delete;

      static void*
      param_factory () = delete;
    };

    typedef
    pgsql::query_column<
      ::obe::title_id,
      pgsql::id_integer,
      title_base_type_ >
    title_type_;

    static const title_type_ title;

    // owner
    //
    struct owner_base_type_: pgsql::query_column_base
    {
      using query_column_base::query_column_base;

      static void
      append (pgsql::query_base& q,
              pgsql::val_bind< ::obe::user_id > v,
              const char* conv)
      {
        // From model.hxx:54:12
        ::uint64_t const& vt =
          std::to_underlying (v.val);

        q.append<
          ::uint64_t,
          pgsql::id_bigint > (
            pgsql::val_bind< ::uint64_t > (vt),
            conv);
      }

      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             std::is_reference< decltype (
                 // From model.hxx:54:12
                 std::to_underlying (r.ref)) >::value>::type
      {
        // From model.hxx:54:12
        ::uint64_t const& rt =
          std::to_underlying (r.ref);

        q.append<
          ::uint64_t,
          pgsql::id_bigint > (
            pgsql::ref_bind< ::uint64_t > (rt),
            conv);
      }

      // If a compiler error points to the line below, then it most likely
      // means that the 'to' clause expression of the respective map pragma is
      // not of a reference type and thus binding by reference is not
      // supported for this query member.
      //
      template <typename T>
      static auto
      append (pgsql::query_base& q,
              pgsql::ref_bind<T> r,
              const char* conv)
        -> typename std::enable_if<
             !std::is_reference< decltype (
                 // From model.hxx:54:12
                 std::to_underlying (r.ref)) >::value>::type
        = delete;

      static void*
      param_factory () = delete;
    };

    typedef
    pgsql::query_column<
      ::obe::user_id,
      pgsql::id_bigint,
      owner_base_type_ >
    owner_type_;

    static const owner_type_ owner;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;

    // flag1
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    flag1_type_;

    static const flag1_type_ flag1;

    // flag2
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    flag2_type_;

    static const flag2_type_ flag2;

    // created
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    created_type_;

    static const created_type_ created;

    // modified
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    modified_type_;

    static const modified_type_ modified;

    // size
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    size_type_;

    static const size_type_ size;

    // data
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::obe::bytes,
        pgsql::id_bytea >::query_type,
      pgsql::id_bytea >
    data_type_;

    static const data_type_ data;
  };

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::id_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::title_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::owner_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  owner (A::table_name, "\"owner\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::name_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::flag1_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  flag1 (A::table_name, "\"flag1\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::flag2_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  flag2 (A::table_name, "\"flag2\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::created_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  created (A::table_name, "\"created\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::modified_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  modified (A::table_name, "\"modified\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::size_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  size (A::table_name, "\"size\"", 0);

  template <typename A>
  const typename query_columns< ::obe::file_record, id_pgsql, A >::data_type_
  query_columns< ::obe::file_record, id_pgsql, A >::
  data (A::table_name, "\"data\"", 0);

  template <typename A>
  struct pointer_query_columns< ::obe::file_record, id_pgsql, A >:
    query_columns< ::obe::file_record, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::obe::file_record, id_pgsql >:
    public access::object_traits< ::obe::file_record >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // title
      //
      int title_value;
      bool title_null;

      // owner
      //
      long long owner_value;
      bool owner_null;

      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // flag1
      //
      bool flag1_value;
      bool flag1_null;

      // flag2
      //
      bool flag2_value;
      bool flag2_null;

      // created
      //
      long long created_value;
      bool created_null;

      // modified
      //
      long long modified_value;
      bool modified_null;

      // size
      //
      int size_value;
      bool size_null;

      // data
      //
      details::buffer data_value;
      std::size_t data_size;
      bool data_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::obe::file_record, id_common >:
    public access::object_traits_impl< ::obe::file_record, id_pgsql >
  {
  };

  // performance_key
  //
  template <>
  class access::composite_value_traits< ::obe::performance_key, id_pgsql >
  {
    public:
    typedef ::obe::performance_key value_type;

    struct image_type
    {
      // title
      //
      int title_value;
      bool title_null;

      // kind
      //
      int kind_value;
      bool kind_null;

      // user
      //
      long long user_value;
      bool user_null;
    };

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          pgsql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              pgsql::statement_kind);

    static const std::size_t column_count = 3UL;
  };

  // performance_record
  //
  template <typename A>
  struct query_columns< ::obe::performance_record, id_pgsql, A >
  {
    // id
    //
    struct id_class_
    {
      id_class_ ()
      {
      }

      // title
      //
      struct title_base_type_: pgsql::query_column_base
      {
        using query_column_base::query_column_base;

        static void
        append (pgsql::query_base& q,
                pgsql::val_bind< ::obe::title_id > v,
                const char* conv)
        {
          // From model.hxx:49:12
          ::uint32_t const& vt =
            std::to_underlying (v.val);

          q.append<
            ::uint32_t,
            pgsql::id_integer > (
              pgsql::val_bind< ::uint32_t > (vt),
              conv);
        }

        template <typename T>
        static auto
        append (pgsql::query_base& q,
                pgsql::ref_bind<T> r,
                const char* conv)
          -> typename std::enable_if<
               std::is_reference< decltype (
                   // From model.hxx:49:12
                   std::to_underlying (r.ref)) >::value>::type
        {
          // From model.hxx:49:12
          ::uint32_t const& rt =
            std::to_underlying (r.ref);

          q.append<
            ::uint32_t,
            pgsql::id_integer > (
              pgsql::ref_bind< ::uint32_t > (rt),
              conv);
        }

        // If a compiler error points to the line below, then it most likely
        // means that the 'to' clause expression of the respective map pragma is
        // not of a reference type and thus binding by reference is not
        // supported for this query member.
        //
        template <typename T>
        static auto
        append (pgsql::query_base& q,
                pgsql::ref_bind<T> r,
                const char* conv)
          -> typename std::enable_if<
               !std::is_reference< decltype (
                   // From model.hxx:49:12
                   std::to_underlying (r.ref)) >::value>::type
          = delete;

        static void*
        param_factory () = delete;
      };

      typedef
      pgsql::query_column<
        ::obe::title_id,
        pgsql::id_integer,
        title_base_type_ >
      title_type_;

      static const title_type_ title;

      // kind
      //
      typedef
      pgsql::query_column<
        pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::query_type,
        pgsql::id_integer >
      kind_type_;

      static const kind_type_ kind;

      // user
      //
      struct user_base_type_: pgsql::query_column_base
      {
        using query_column_base::query_column_base;

        static void
        append (pgsql::query_base& q,
                pgsql::val_bind< ::obe::user_id > v,
                const char* conv)
        {
          // From model.hxx:54:12
          ::uint64_t const& vt =
            std::to_underlying (v.val);

          q.append<
            ::uint64_t,
            pgsql::id_bigint > (
              pgsql::val_bind< ::uint64_t > (vt),
              conv);
        }

        template <typename T>
        static auto
        append (pgsql::query_base& q,
                pgsql::ref_bind<T> r,
                const char* conv)
          -> typename std::enable_if<
               std::is_reference< decltype (
                   // From model.hxx:54:12
                   std::to_underlying (r.ref)) >::value>::type
        {
          // From model.hxx:54:12
          ::uint64_t const& rt =
            std::to_underlying (r.ref);

          q.append<
            ::uint64_t,
            pgsql::id_bigint > (
              pgsql::ref_bind< ::uint64_t > (rt),
              conv);
        }

        // If a compiler error points to the line below, then it most likely
        // means that the 'to' clause expression of the respective map pragma is
        // not of a reference type and thus binding by reference is not
        // supported for this query member.
        //
        template <typename T>
        static auto
        append (pgsql::query_base& q,
                pgsql::ref_bind<T> r,
                const char* conv)
          -> typename std::enable_if<
               !std::is_reference< decltype (
                   // From model.hxx:54:12
                   std::to_underlying (r.ref)) >::value>::type
          = delete;

        static void*
        param_factory () = delete;
      };

      typedef
      pgsql::query_column<
        ::obe::user_id,
        pgsql::id_bigint,
        user_base_type_ >
      user_type_;

      static const user_type_ user;
    };

    static const id_class_ id;

    // value
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    value_type_;

    static const value_type_ value;
  };

  template <typename A>
  const typename query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::title_type_
  query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::kind_type_
  query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::
  kind (A::table_name, "\"kind\"", 0);

  template <typename A>
  const typename query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::user_type_
  query_columns< ::obe::performance_record, id_pgsql, A >::id_class_::
  user (A::table_name, "\"user\"", 0);

  template <typename A>
  const typename query_columns< ::obe::performance_record, id_pgsql, A >::id_class_
  query_columns< ::obe::performance_record, id_pgsql, A >::id;

  template <typename A>
  const typename query_columns< ::obe::performance_record, id_pgsql, A >::value_type_
  query_columns< ::obe::performance_record, id_pgsql, A >::
  value (A::table_name, "\"value\"", 0);

  template <typename A>
  struct pointer_query_columns< ::obe::performance_record, id_pgsql, A >:
    query_columns< ::obe::performance_record, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::obe::performance_record, id_pgsql >:
    public access::object_traits< ::obe::performance_record >
  {
    public:
    struct id_image_type
    {
      composite_value_traits< ::obe::performance_key, id_pgsql >::image_type id_value;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      composite_value_traits< ::obe::performance_key, id_pgsql >::image_type id_value;

      // value
      //
      long long value_value;
      bool value_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 3UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::obe::performance_record, id_common >:
    public access::object_traits_impl< ::obe::performance_record, id_pgsql >
  {
  };

  // file_record_header
  //
  template <>
  class access::view_traits_impl< ::obe::file_record_header, id_pgsql >:
    public access::view_traits< ::obe::file_record_header >
  {
    public:
    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // title
      //
      int title_value;
      bool title_null;

      // owner
      //
      long long owner_value;
      bool owner_null;

      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // flag1
      //
      bool flag1_value;
      bool flag1_null;

      // flag2
      //
      bool flag2_value;
      bool flag2_null;

      // created
      //
      long long created_value;
      bool created_null;

      // modified
      //
      long long modified_value;
      bool modified_null;

      // size
      //
      int size_value;
      bool size_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 9UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::obe::file_record_header, id_common >:
    public access::view_traits_impl< ::obe::file_record_header, id_pgsql >
  {
  };

  // file_record_count
  //
  template <>
  class access::view_traits_impl< ::obe::file_record_count, id_pgsql >:
    public access::view_traits< ::obe::file_record_count >
  {
    public:
    struct image_type
    {
      // result
      //
      long long result_value;
      bool result_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::obe::file_record_count, id_common >:
    public access::view_traits_impl< ::obe::file_record_count, id_pgsql >
  {
  };

  // file_record
  //
  // file_record_header
  //
  struct access::view_traits_impl< ::obe::file_record_header, id_pgsql >::query_columns:
    odb::pointer_query_columns<
      ::obe::file_record,
      id_pgsql,
      odb::access::object_traits_impl< ::obe::file_record, id_pgsql > >
  {
  };

  // file_record_count
  //
  struct access::view_traits_impl< ::obe::file_record_count, id_pgsql >::query_columns:
    odb::pointer_query_columns<
      ::obe::file_record,
      id_pgsql,
      odb::access::object_traits_impl< ::obe::file_record, id_pgsql > >
  {
  };

  // performance_record
  //
}

#include <libobe/model-odb.ixx>

#include <odb/post.hxx>

#endif // LIBOBE_MODEL_ODB_HXX
