// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef OBE_OBE_OPTIONS_HXX
#define OBE_OBE_OPTIONS_HXX

// Begin prologue.
//
//
// End prologue.

#include <list>
#include <deque>
#include <iosfwd>
#include <string>
#include <cstddef>
#include <exception>

#ifndef CLI_POTENTIALLY_UNUSED
#  if defined(_MSC_VER) || defined(__xlC__)
#    define CLI_POTENTIALLY_UNUSED(x) (void*)&x
#  else
#    define CLI_POTENTIALLY_UNUSED(x) (void)x
#  endif
#endif

namespace obe
{
  namespace cli
  {
    class usage_para
    {
      public:
      enum value
      {
        none,
        text,
        option
      };

      usage_para (value);

      operator value () const 
      {
        return v_;
      }

      private:
      value v_;
    };

    class unknown_mode
    {
      public:
      enum value
      {
        skip,
        stop,
        fail
      };

      unknown_mode (value);

      operator value () const 
      {
        return v_;
      }

      private:
      value v_;
    };

    // Exceptions.
    //

    class exception: public std::exception
    {
      public:
      virtual void
      print (::std::ostream&) const = 0;
    };

    ::std::ostream&
    operator<< (::std::ostream&, const exception&);

    class unknown_option: public exception
    {
      public:
      virtual
      ~unknown_option () noexcept;

      unknown_option (const std::string& option);

      const std::string&
      option () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string option_;
    };

    class unknown_argument: public exception
    {
      public:
      virtual
      ~unknown_argument () noexcept;

      unknown_argument (const std::string& argument);

      const std::string&
      argument () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string argument_;
    };

    class missing_value: public exception
    {
      public:
      virtual
      ~missing_value () noexcept;

      missing_value (const std::string& option);

      const std::string&
      option () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string option_;
    };

    class invalid_value: public exception
    {
      public:
      virtual
      ~invalid_value () noexcept;

      invalid_value (const std::string& option,
                     const std::string& value,
                     const std::string& message = std::string ());

      const std::string&
      option () const;

      const std::string&
      value () const;

      const std::string&
      message () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string option_;
      std::string value_;
      std::string message_;
    };

    class eos_reached: public exception
    {
      public:
      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;
    };

    class file_io_failure: public exception
    {
      public:
      virtual
      ~file_io_failure () noexcept;

      file_io_failure (const std::string& file);

      const std::string&
      file () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string file_;
    };

    class unmatched_quote: public exception
    {
      public:
      virtual
      ~unmatched_quote () noexcept;

      unmatched_quote (const std::string& argument);

      const std::string&
      argument () const;

      virtual void
      print (::std::ostream&) const;

      virtual const char*
      what () const noexcept;

      private:
      std::string argument_;
    };

    // Command line argument scanner interface.
    //
    // The values returned by next() are guaranteed to be valid
    // for the two previous arguments up until a call to a third
    // peek() or next().
    //
    // The position() function returns a monotonically-increasing
    // number which, if stored, can later be used to determine the
    // relative position of the argument returned by the following
    // call to next(). Note that if multiple scanners are used to
    // extract arguments from multiple sources, then the end
    // position of the previous scanner should be used as the
    // start position of the next.
    //
    class scanner
    {
      public:
      virtual
      ~scanner ();

      virtual bool
      more () = 0;

      virtual const char*
      peek () = 0;

      virtual const char*
      next () = 0;

      virtual void
      skip () = 0;

      virtual std::size_t
      position () = 0;
    };

    class argv_scanner: public scanner
    {
      public:
      argv_scanner (int& argc,
                    char** argv,
                    bool erase = false,
                    std::size_t start_position = 0);

      argv_scanner (int start,
                    int& argc,
                    char** argv,
                    bool erase = false,
                    std::size_t start_position = 0);

      int
      end () const;

      virtual bool
      more ();

      virtual const char*
      peek ();

      virtual const char*
      next ();

      virtual void
      skip ();

      virtual std::size_t
      position ();

      protected:
      std::size_t start_position_;
      int i_;
      int& argc_;
      char** argv_;
      bool erase_;
    };

    class argv_file_scanner: public argv_scanner
    {
      public:
      argv_file_scanner (int& argc,
                         char** argv,
                         const std::string& option,
                         bool erase = false,
                         std::size_t start_position = 0);

      argv_file_scanner (int start,
                         int& argc,
                         char** argv,
                         const std::string& option,
                         bool erase = false,
                         std::size_t start_position = 0);

      argv_file_scanner (const std::string& file,
                         const std::string& option,
                         std::size_t start_position = 0);

      struct option_info
      {
        // If search_func is not NULL, it is called, with the arg
        // value as the second argument, to locate the options file.
        // If it returns an empty string, then the file is ignored.
        //
        const char* option;
        std::string (*search_func) (const char*, void* arg);
        void* arg;
      };

      argv_file_scanner (int& argc,
                          char** argv,
                          const option_info* options,
                          std::size_t options_count,
                          bool erase = false,
                          std::size_t start_position = 0);

      argv_file_scanner (int start,
                         int& argc,
                         char** argv,
                         const option_info* options,
                         std::size_t options_count,
                         bool erase = false,
                         std::size_t start_position = 0);

      argv_file_scanner (const std::string& file,
                         const option_info* options = 0,
                         std::size_t options_count = 0,
                         std::size_t start_position = 0);

      virtual bool
      more ();

      virtual const char*
      peek ();

      virtual const char*
      next ();

      virtual void
      skip ();

      virtual std::size_t
      position ();

      // Return the file path if the peeked at argument came from a file and
      // the empty string otherwise. The reference is guaranteed to be valid
      // till the end of the scanner lifetime.
      //
      const std::string&
      peek_file ();

      // Return the 1-based line number if the peeked at argument came from
      // a file and zero otherwise.
      //
      std::size_t
      peek_line ();

      private:
      const option_info*
      find (const char*) const;

      void
      load (const std::string& file);

      typedef argv_scanner base;

      const std::string option_;
      option_info option_info_;
      const option_info* options_;
      std::size_t options_count_;

      struct arg
      {
        std::string value;
        const std::string* file;
        std::size_t line;
      };

      std::deque<arg> args_;
      std::list<std::string> files_;

      // Circular buffer of two arguments.
      //
      std::string hold_[2];
      std::size_t i_;

      bool skip_;

      static int zero_argc_;
      static std::string empty_string_;
    };

    template <typename X>
    struct parser;
  }
}

#include <string>

#include <vector>

#include <cstddef>

#include <cstdint>

namespace obe
{
  class options
  {
    public:
    options ();

    // Return true if anything has been parsed.
    //
    bool
    parse (int& argc,
           char** argv,
           bool erase = false,
           ::obe::cli::unknown_mode option = ::obe::cli::unknown_mode::fail,
           ::obe::cli::unknown_mode argument = ::obe::cli::unknown_mode::stop);

    bool
    parse (int start,
           int& argc,
           char** argv,
           bool erase = false,
           ::obe::cli::unknown_mode option = ::obe::cli::unknown_mode::fail,
           ::obe::cli::unknown_mode argument = ::obe::cli::unknown_mode::stop);

    bool
    parse (int& argc,
           char** argv,
           int& end,
           bool erase = false,
           ::obe::cli::unknown_mode option = ::obe::cli::unknown_mode::fail,
           ::obe::cli::unknown_mode argument = ::obe::cli::unknown_mode::stop);

    bool
    parse (int start,
           int& argc,
           char** argv,
           int& end,
           bool erase = false,
           ::obe::cli::unknown_mode option = ::obe::cli::unknown_mode::fail,
           ::obe::cli::unknown_mode argument = ::obe::cli::unknown_mode::stop);

    bool
    parse (::obe::cli::scanner&,
           ::obe::cli::unknown_mode option = ::obe::cli::unknown_mode::fail,
           ::obe::cli::unknown_mode argument = ::obe::cli::unknown_mode::stop);

    // Option accessors.
    //
    const bool&
    help () const;

    const bool&
    version () const;

    const std::string&
    options_file () const;

    bool
    options_file_specified () const;

    const bool&
    v () const;

    const bool&
    V () const;

    const bool&
    quiet () const;

    const std::uint16_t&
    verbose () const;

    bool
    verbose_specified () const;

    const std::string&
    auth_address () const;

    bool
    auth_address_specified () const;

    const std::uint16_t&
    auth_port () const;

    bool
    auth_port_specified () const;

    const std::string&
    lsg_address () const;

    bool
    lsg_address_specified () const;

    const std::uint16_t&
    lsg_port () const;

    bool
    lsg_port_specified () const;

    const std::string&
    bandwidth_address () const;

    bool
    bandwidth_address_specified () const;

    const std::uint16_t&
    bandwidth_port () const;

    bool
    bandwidth_port_specified () const;

    const std::string&
    bandwidth_public_address () const;

    bool
    bandwidth_public_address_specified () const;

    const std::uint16_t&
    bandwidth_public_port () const;

    bool
    bandwidth_public_port_specified () const;

    const std::string&
    tls_certificate () const;

    bool
    tls_certificate_specified () const;

    const std::string&
    tls_key () const;

    bool
    tls_key_specified () const;

    const std::string&
    ticket_key () const;

    bool
    ticket_key_specified () const;

    const std::vector<std::uint32_t>&
    title () const;

    bool
    title_specified () const;

    const std::uint32_t&
    ticket_lifetime () const;

    bool
    ticket_lifetime_specified () const;

    const std::string&
    sandbox () const;

    bool
    sandbox_specified () const;

    const std::string&
    platform () const;

    bool
    platform_specified () const;

    const std::string&
    publisher_files () const;

    bool
    publisher_files_specified () const;

    const bool&
    print_endpoints () const;

    const std::string&
    db_name () const;

    bool
    db_name_specified () const;

    const std::string&
    db_user () const;

    bool
    db_user_specified () const;

    const std::string&
    db_password () const;

    bool
    db_password_specified () const;

    const std::string&
    db_host () const;

    bool
    db_host_specified () const;

    const std::uint16_t&
    db_port () const;

    bool
    db_port_specified () const;

    const std::size_t&
    db_max_connections () const;

    bool
    db_max_connections_specified () const;

    const std::size_t&
    db_retry () const;

    bool
    db_retry_specified () const;

    const bool&
    migrate () const;

    const bool&
    insecure_authentication () const;

    // Print usage information.
    //
    static ::obe::cli::usage_para
    print_usage (::std::ostream&,
                 ::obe::cli::usage_para = ::obe::cli::usage_para::none);

    // Implementation details.
    //
    protected:
    bool
    _parse (const char*, ::obe::cli::scanner&);

    private:
    bool
    _parse (::obe::cli::scanner&,
            ::obe::cli::unknown_mode option,
            ::obe::cli::unknown_mode argument);

    public:
    bool help_;
    bool version_;
    std::string options_file_;
    bool options_file_specified_;
    bool v_;
    bool V_;
    bool quiet_;
    std::uint16_t verbose_;
    bool verbose_specified_;
    std::string auth_address_;
    bool auth_address_specified_;
    std::uint16_t auth_port_;
    bool auth_port_specified_;
    std::string lsg_address_;
    bool lsg_address_specified_;
    std::uint16_t lsg_port_;
    bool lsg_port_specified_;
    std::string bandwidth_address_;
    bool bandwidth_address_specified_;
    std::uint16_t bandwidth_port_;
    bool bandwidth_port_specified_;
    std::string bandwidth_public_address_;
    bool bandwidth_public_address_specified_;
    std::uint16_t bandwidth_public_port_;
    bool bandwidth_public_port_specified_;
    std::string tls_certificate_;
    bool tls_certificate_specified_;
    std::string tls_key_;
    bool tls_key_specified_;
    std::string ticket_key_;
    bool ticket_key_specified_;
    std::vector<std::uint32_t> title_;
    bool title_specified_;
    std::uint32_t ticket_lifetime_;
    bool ticket_lifetime_specified_;
    std::string sandbox_;
    bool sandbox_specified_;
    std::string platform_;
    bool platform_specified_;
    std::string publisher_files_;
    bool publisher_files_specified_;
    bool print_endpoints_;
    std::string db_name_;
    bool db_name_specified_;
    std::string db_user_;
    bool db_user_specified_;
    std::string db_password_;
    bool db_password_specified_;
    std::string db_host_;
    bool db_host_specified_;
    std::uint16_t db_port_;
    bool db_port_specified_;
    std::size_t db_max_connections_;
    bool db_max_connections_specified_;
    std::size_t db_retry_;
    bool db_retry_specified_;
    bool migrate_;
    bool insecure_authentication_;
  };
}

// Print page usage information.
//
namespace obe
{
  ::obe::cli::usage_para
  print_obe_usage (::std::ostream&,
                   ::obe::cli::usage_para = ::obe::cli::usage_para::none);
}

#include <obe/obe-options.ixx>

// Begin epilogue.
//
//
// End epilogue.

#endif // OBE_OBE_OPTIONS_HXX
