// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

#include <obe/obe-options.hxx>

#include <map>
#include <set>
#include <string>
#include <vector>
#include <utility>
#include <ostream>
#include <sstream>
#include <cstring>
#include <fstream>

namespace obe
{
  namespace cli
  {
    // unknown_option
    //
    unknown_option::
    ~unknown_option () noexcept
    {
    }

    void unknown_option::
    print (::std::ostream& os) const
    {
      os << "unknown option '" << option ().c_str () << "'";
    }

    const char* unknown_option::
    what () const noexcept
    {
      return "unknown option";
    }

    // unknown_argument
    //
    unknown_argument::
    ~unknown_argument () noexcept
    {
    }

    void unknown_argument::
    print (::std::ostream& os) const
    {
      os << "unknown argument '" << argument ().c_str () << "'";
    }

    const char* unknown_argument::
    what () const noexcept
    {
      return "unknown argument";
    }

    // missing_value
    //
    missing_value::
    ~missing_value () noexcept
    {
    }

    void missing_value::
    print (::std::ostream& os) const
    {
      os << "missing value for option '" << option ().c_str () << "'";
    }

    const char* missing_value::
    what () const noexcept
    {
      return "missing option value";
    }

    // invalid_value
    //
    invalid_value::
    ~invalid_value () noexcept
    {
    }

    void invalid_value::
    print (::std::ostream& os) const
    {
      os << "invalid value '" << value ().c_str () << "' for option '"
         << option ().c_str () << "'";

      if (!message ().empty ())
        os << ": " << message ().c_str ();
    }

    const char* invalid_value::
    what () const noexcept
    {
      return "invalid option value";
    }

    // eos_reached
    //
    void eos_reached::
    print (::std::ostream& os) const
    {
      os << what ();
    }

    const char* eos_reached::
    what () const noexcept
    {
      return "end of argument stream reached";
    }

    // file_io_failure
    //
    file_io_failure::
    ~file_io_failure () noexcept
    {
    }

    void file_io_failure::
    print (::std::ostream& os) const
    {
      os << "unable to open file '" << file ().c_str () << "' or read failure";
    }

    const char* file_io_failure::
    what () const noexcept
    {
      return "unable to open file or read failure";
    }

    // unmatched_quote
    //
    unmatched_quote::
    ~unmatched_quote () noexcept
    {
    }

    void unmatched_quote::
    print (::std::ostream& os) const
    {
      os << "unmatched quote in argument '" << argument ().c_str () << "'";
    }

    const char* unmatched_quote::
    what () const noexcept
    {
      return "unmatched quote";
    }

    // scanner
    //
    scanner::
    ~scanner ()
    {
    }

    // argv_scanner
    //
    bool argv_scanner::
    more ()
    {
      return i_ < argc_;
    }

    const char* argv_scanner::
    peek ()
    {
      if (i_ < argc_)
        return argv_[i_];
      else
        throw eos_reached ();
    }

    const char* argv_scanner::
    next ()
    {
      if (i_ < argc_)
      {
        const char* r (argv_[i_]);

        if (erase_)
        {
          for (int i (i_ + 1); i < argc_; ++i)
            argv_[i - 1] = argv_[i];

          --argc_;
          argv_[argc_] = 0;
        }
        else
          ++i_;

        ++start_position_;
        return r;
      }
      else
        throw eos_reached ();
    }

    void argv_scanner::
    skip ()
    {
      if (i_ < argc_)
      {
        ++i_;
        ++start_position_;
      }
      else
        throw eos_reached ();
    }

    std::size_t argv_scanner::
    position ()
    {
      return start_position_;
    }

    // argv_file_scanner
    //
    int argv_file_scanner::zero_argc_ = 0;
    std::string argv_file_scanner::empty_string_;

    bool argv_file_scanner::
    more ()
    {
      if (!args_.empty ())
        return true;

      while (base::more ())
      {
        // See if the next argument is the file option.
        //
        const char* a (base::peek ());
        const option_info* oi = 0;
        const char* ov = 0;

        if (!skip_)
        {
          if ((oi = find (a)) != 0)
          {
            base::next ();

            if (!base::more ())
              throw missing_value (a);

            ov = base::next ();
          }
          else if (std::strncmp (a, "-", 1) == 0)
          {
            if ((ov = std::strchr (a, '=')) != 0)
            {
              std::string o (a, 0, ov - a);
              if ((oi = find (o.c_str ())) != 0)
              {
                base::next ();
                ++ov;
              }
            }
          }
        }

        if (oi != 0)
        {
          if (oi->search_func != 0)
          {
            std::string f (oi->search_func (ov, oi->arg));

            if (!f.empty ())
              load (f);
          }
          else
            load (ov);

          if (!args_.empty ())
            return true;
        }
        else
        {
          if (!skip_)
            skip_ = (std::strcmp (a, "--") == 0);

          return true;
        }
      }

      return false;
    }

    const char* argv_file_scanner::
    peek ()
    {
      if (!more ())
        throw eos_reached ();

      return args_.empty () ? base::peek () : args_.front ().value.c_str ();
    }

    const std::string& argv_file_scanner::
    peek_file ()
    {
      if (!more ())
        throw eos_reached ();

      return args_.empty () ? empty_string_ : *args_.front ().file;
    }

    std::size_t argv_file_scanner::
    peek_line ()
    {
      if (!more ())
        throw eos_reached ();

      return args_.empty () ? 0 : args_.front ().line;
    }

    const char* argv_file_scanner::
    next ()
    {
      if (!more ())
        throw eos_reached ();

      if (args_.empty ())
        return base::next ();
      else
      {
        hold_[i_ == 0 ? ++i_ : --i_].swap (args_.front ().value);
        args_.pop_front ();
        ++start_position_;
        return hold_[i_].c_str ();
      }
    }

    void argv_file_scanner::
    skip ()
    {
      if (!more ())
        throw eos_reached ();

      if (args_.empty ())
        return base::skip ();
      else
      {
        args_.pop_front ();
        ++start_position_;
      }
    }

    const argv_file_scanner::option_info* argv_file_scanner::
    find (const char* a) const
    {
      for (std::size_t i (0); i < options_count_; ++i)
        if (std::strcmp (a, options_[i].option) == 0)
          return &options_[i];

      return 0;
    }

    std::size_t argv_file_scanner::
    position ()
    {
      return start_position_;
    }

    void argv_file_scanner::
    load (const std::string& file)
    {
      using namespace std;

      ifstream is (file.c_str ());

      if (!is.is_open ())
        throw file_io_failure (file);

      files_.push_back (file);

      arg a;
      a.file = &*files_.rbegin ();

      for (a.line = 1; !is.eof (); ++a.line)
      {
        string line;
        getline (is, line);

        if (is.fail () && !is.eof ())
          throw file_io_failure (file);

        string::size_type n (line.size ());

        // Trim the line from leading and trailing whitespaces.
        //
        if (n != 0)
        {
          const char* f (line.c_str ());
          const char* l (f + n);

          const char* of (f);
          while (f < l && (*f == ' ' || *f == '\t' || *f == '\r'))
            ++f;

          --l;

          const char* ol (l);
          while (l > f && (*l == ' ' || *l == '\t' || *l == '\r'))
            --l;

          if (f != of || l != ol)
            line = f <= l ? string (f, l - f + 1) : string ();
        }

        // Ignore empty lines, those that start with #.
        //
        if (line.empty () || line[0] == '#')
          continue;

        string::size_type p (string::npos);
        if (line.compare (0, 1, "-") == 0)
        {
          p = line.find (' ');

          string::size_type q (line.find ('='));
          if (q != string::npos && q < p)
            p = q;
        }

        string s1;
        if (p != string::npos)
        {
          s1.assign (line, 0, p);

          // Skip leading whitespaces in the argument.
          //
          if (line[p] == '=')
            ++p;
          else
          {
            n = line.size ();
            for (++p; p < n; ++p)
            {
              char c (line[p]);
              if (c != ' ' && c != '\t' && c != '\r')
                break;
            }
          }
        }
        else if (!skip_)
          skip_ = (line == "--");

        string s2 (line, p != string::npos ? p : 0);

        // If the string (which is an option value or argument) is
        // wrapped in quotes, remove them.
        //
        n = s2.size ();
        char cf (s2[0]), cl (s2[n - 1]);

        if (cf == '"' || cf == '\'' || cl == '"' || cl == '\'')
        {
          if (n == 1 || cf != cl)
            throw unmatched_quote (s2);

          s2 = string (s2, 1, n - 2);
        }

        if (!s1.empty ())
        {
          // See if this is another file option.
          //
          const option_info* oi;
          if (!skip_ && (oi = find (s1.c_str ())))
          {
            if (s2.empty ())
              throw missing_value (oi->option);

            if (oi->search_func != 0)
            {
              string f (oi->search_func (s2.c_str (), oi->arg));
              if (!f.empty ())
                load (f);
            }
            else
            {
              // If the path of the file being parsed is not simple and the
              // path of the file that needs to be loaded is relative, then
              // complete the latter using the former as a base.
              //
#ifndef _WIN32
              string::size_type p (file.find_last_of ('/'));
              bool c (p != string::npos && s2[0] != '/');
#else
              string::size_type p (file.find_last_of ("/\\"));
              bool c (p != string::npos && s2[1] != ':');
#endif
              if (c)
                s2.insert (0, file, 0, p + 1);

              load (s2);
            }

            continue;
          }

          a.value = s1;
          args_.push_back (a);
        }

        a.value = s2;
        args_.push_back (a);
      }
    }

    template <typename X>
    struct parser
    {
      static void
      parse (X& x, bool& xs, scanner& s)
      {
        using namespace std;

        const char* o (s.next ());
        if (s.more ())
        {
          string v (s.next ());
          istringstream is (v);
          if (!(is >> x && is.peek () == istringstream::traits_type::eof ()))
            throw invalid_value (o, v);
        }
        else
          throw missing_value (o);

        xs = true;
      }
    };

    template <>
    struct parser<bool>
    {
      static void
      parse (bool& x, bool& xs, scanner& s)
      {
        const char* o (s.next ());

        if (s.more ())
        {
          const char* v (s.next ());

          if (std::strcmp (v, "1")    == 0 ||
              std::strcmp (v, "true") == 0 ||
              std::strcmp (v, "TRUE") == 0 ||
              std::strcmp (v, "True") == 0)
            x = true;
          else if (std::strcmp (v, "0")     == 0 ||
                   std::strcmp (v, "false") == 0 ||
                   std::strcmp (v, "FALSE") == 0 ||
                   std::strcmp (v, "False") == 0)
            x = false;
          else
            throw invalid_value (o, v);
        }
        else
          throw missing_value (o);

        xs = true;
      }
    };

    template <>
    struct parser<std::string>
    {
      static void
      parse (std::string& x, bool& xs, scanner& s)
      {
        const char* o (s.next ());

        if (s.more ())
          x = s.next ();
        else
          throw missing_value (o);

        xs = true;
      }
    };

    template <typename X>
    struct parser<std::pair<X, std::size_t> >
    {
      static void
      parse (std::pair<X, std::size_t>& x, bool& xs, scanner& s)
      {
        x.second = s.position ();
        parser<X>::parse (x.first, xs, s);
      }
    };

    template <typename X>
    struct parser<std::vector<X> >
    {
      static void
      parse (std::vector<X>& c, bool& xs, scanner& s)
      {
        X x;
        bool dummy;
        parser<X>::parse (x, dummy, s);
        c.push_back (x);
        xs = true;
      }
    };

    template <typename X, typename C>
    struct parser<std::set<X, C> >
    {
      static void
      parse (std::set<X, C>& c, bool& xs, scanner& s)
      {
        X x;
        bool dummy;
        parser<X>::parse (x, dummy, s);
        c.insert (x);
        xs = true;
      }
    };

    template <typename K, typename V, typename C>
    struct parser<std::map<K, V, C> >
    {
      static void
      parse (std::map<K, V, C>& m, bool& xs, scanner& s)
      {
        const char* o (s.next ());

        if (s.more ())
        {
          std::size_t pos (s.position ());
          std::string ov (s.next ());
          std::string::size_type p = ov.find ('=');

          K k = K ();
          V v = V ();
          std::string kstr (ov, 0, p);
          std::string vstr (ov, (p != std::string::npos ? p + 1 : ov.size ()));

          int ac (2);
          char* av[] =
          {
            const_cast<char*> (o),
            0
          };

          bool dummy;
          if (!kstr.empty ())
          {
            av[1] = const_cast<char*> (kstr.c_str ());
            argv_scanner s (0, ac, av, false, pos);
            parser<K>::parse (k, dummy, s);
          }

          if (!vstr.empty ())
          {
            av[1] = const_cast<char*> (vstr.c_str ());
            argv_scanner s (0, ac, av, false, pos);
            parser<V>::parse (v, dummy, s);
          }

          m[k] = v;
        }
        else
          throw missing_value (o);

        xs = true;
      }
    };

    template <typename K, typename V, typename C>
    struct parser<std::multimap<K, V, C> >
    {
      static void
      parse (std::multimap<K, V, C>& m, bool& xs, scanner& s)
      {
        const char* o (s.next ());

        if (s.more ())
        {
          std::size_t pos (s.position ());
          std::string ov (s.next ());
          std::string::size_type p = ov.find ('=');

          K k = K ();
          V v = V ();
          std::string kstr (ov, 0, p);
          std::string vstr (ov, (p != std::string::npos ? p + 1 : ov.size ()));

          int ac (2);
          char* av[] =
          {
            const_cast<char*> (o),
            0
          };

          bool dummy;
          if (!kstr.empty ())
          {
            av[1] = const_cast<char*> (kstr.c_str ());
            argv_scanner s (0, ac, av, false, pos);
            parser<K>::parse (k, dummy, s);
          }

          if (!vstr.empty ())
          {
            av[1] = const_cast<char*> (vstr.c_str ());
            argv_scanner s (0, ac, av, false, pos);
            parser<V>::parse (v, dummy, s);
          }

          m.insert (typename std::multimap<K, V, C>::value_type (k, v));
        }
        else
          throw missing_value (o);

        xs = true;
      }
    };

    template <typename X, typename T, T X::*M>
    void
    thunk (X& x, scanner& s)
    {
      parser<T>::parse (x.*M, s);
    }

    template <typename X, bool X::*M>
    void
    thunk (X& x, scanner& s)
    {
      s.next ();
      x.*M = true;
    }

    template <typename X, typename T, T X::*M, bool X::*S>
    void
    thunk (X& x, scanner& s)
    {
      parser<T>::parse (x.*M, x.*S, s);
    }
  }
}

#include <map>

namespace obe
{
  // options
  //

  options::
  options ()
  : help_ (),
    version_ (),
    options_file_ (),
    options_file_specified_ (false),
    v_ (),
    V_ (),
    quiet_ (),
    verbose_ (1),
    verbose_specified_ (false),
    auth_address_ ("0.0.0.0"),
    auth_address_specified_ (false),
    auth_port_ (443),
    auth_port_specified_ (false),
    lsg_address_ ("0.0.0.0"),
    lsg_address_specified_ (false),
    lsg_port_ (3074),
    lsg_port_specified_ (false),
    bandwidth_address_ ("0.0.0.0"),
    bandwidth_address_specified_ (false),
    bandwidth_port_ (3075),
    bandwidth_port_specified_ (false),
    bandwidth_public_address_ (),
    bandwidth_public_address_specified_ (false),
    bandwidth_public_port_ (0),
    bandwidth_public_port_specified_ (false),
    tls_certificate_ (),
    tls_certificate_specified_ (false),
    tls_key_ (),
    tls_key_specified_ (false),
    ticket_key_ (),
    ticket_key_specified_ (false),
    title_ (),
    title_specified_ (false),
    ticket_lifetime_ (3600),
    ticket_lifetime_specified_ (false),
    sandbox_ ("RETAIL"),
    sandbox_specified_ (false),
    platform_ ("PC"),
    platform_specified_ (false),
    publisher_files_ (),
    publisher_files_specified_ (false),
    print_endpoints_ (),
    db_name_ (),
    db_name_specified_ (false),
    db_user_ (),
    db_user_specified_ (false),
    db_password_ (),
    db_password_specified_ (false),
    db_host_ (),
    db_host_specified_ (false),
    db_port_ (0),
    db_port_specified_ (false),
    db_max_connections_ (5),
    db_max_connections_specified_ (false),
    db_retry_ (10),
    db_retry_specified_ (false),
    migrate_ (),
    insecure_authentication_ ()
  {
  }

  bool options::
  parse (int& argc,
         char** argv,
         bool erase,
         ::obe::cli::unknown_mode opt,
         ::obe::cli::unknown_mode arg)
  {
    ::obe::cli::argv_scanner s (argc, argv, erase);
    bool r = _parse (s, opt, arg);
    return r;
  }

  bool options::
  parse (int start,
         int& argc,
         char** argv,
         bool erase,
         ::obe::cli::unknown_mode opt,
         ::obe::cli::unknown_mode arg)
  {
    ::obe::cli::argv_scanner s (start, argc, argv, erase);
    bool r = _parse (s, opt, arg);
    return r;
  }

  bool options::
  parse (int& argc,
         char** argv,
         int& end,
         bool erase,
         ::obe::cli::unknown_mode opt,
         ::obe::cli::unknown_mode arg)
  {
    ::obe::cli::argv_scanner s (argc, argv, erase);
    bool r = _parse (s, opt, arg);
    end = s.end ();
    return r;
  }

  bool options::
  parse (int start,
         int& argc,
         char** argv,
         int& end,
         bool erase,
         ::obe::cli::unknown_mode opt,
         ::obe::cli::unknown_mode arg)
  {
    ::obe::cli::argv_scanner s (start, argc, argv, erase);
    bool r = _parse (s, opt, arg);
    end = s.end ();
    return r;
  }

  bool options::
  parse (::obe::cli::scanner& s,
         ::obe::cli::unknown_mode opt,
         ::obe::cli::unknown_mode arg)
  {
    bool r = _parse (s, opt, arg);
    return r;
  }

  ::obe::cli::usage_para options::
  print_usage (::std::ostream& os, ::obe::cli::usage_para p)
  {
    CLI_POTENTIALLY_UNUSED (os);

    if (p != ::obe::cli::usage_para::none)
      os << ::std::endl;

    os << "\033[1mOPTIONS\033[0m" << ::std::endl;

    os << std::endl
       << "\033[1m--help\033[0m                          Print usage information and exit." << ::std::endl;

    os << std::endl
       << "\033[1m--version\033[0m                       Print version and exit." << ::std::endl;

    os << std::endl
       << "\033[1m--options-file\033[0m \033[4mfile\033[0m             Read additional options from \033[4mfile\033[0m. Each option" << ::std::endl
       << "                                should appear on a separate line optionally" << ::std::endl
       << "                                followed by space or equal sign (\033[1m=\033[0m) and an" << ::std::endl
       << "                                option value. Empty lines and lines starting" << ::std::endl
       << "                                with \033[1m#\033[0m are ignored." << ::std::endl;

    os << std::endl
       << "\033[1m-v\033[0m                              Print informational messages, such as the" << ::std::endl
       << "                                listening endpoints. This is equivalent to" << ::std::endl
       << "                                \033[1m--verbose 2\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m-V\033[0m                              Print trace messages, such as where the stored" << ::std::endl
       << "                                files are kept. This is equivalent to \033[1m--verbose" << ::std::endl
       << "                                3\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--quiet\033[0m|\033[1m-q\033[0m                      Print errors only. This is equivalent to" << ::std::endl
       << "                                \033[1m--verbose 0\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--verbose\033[0m \033[4mlevel\033[0m                 Set the diagnostics verbosity to \033[4mlevel\033[0m between" << ::std::endl
       << "                                0 and 3. Level 0 prints errors only, level 1" << ::std::endl
       << "                                (the default) also warnings, level 2 also" << ::std::endl
       << "                                informational messages, and level 3 also trace" << ::std::endl
       << "                                messages. Note that the diagnostics of the" << ::std::endl
       << "                                servers themselves (for example, the failed" << ::std::endl
       << "                                gateway tasks) are currently printed regardless" << ::std::endl
       << "                                of the verbosity." << ::std::endl;

    os << std::endl
       << "\033[1m--auth-address\033[0m \033[4maddr\033[0m             Listen for the authentication requests on \033[4maddr\033[0m." << ::std::endl
       << "                                The default is all IPv4 interfaces." << ::std::endl;

    os << std::endl
       << "\033[1m--auth-port\033[0m \033[4mport\033[0m                Listen for the authentication requests on \033[4mport\033[0m." << ::std::endl
       << "                                The default is 443. If \033[4mport\033[0m is 0, then the" << ::std::endl
       << "                                system chooses a free port (see" << ::std::endl
       << "                                \033[1m--print-endpoints\033[0m)." << ::std::endl;

    os << std::endl
       << "\033[1m--lsg-address\033[0m \033[4maddr\033[0m              Listen for the lobby service gateway" << ::std::endl
       << "                                connections on \033[4maddr\033[0m. The default is all IPv4" << ::std::endl
       << "                                interfaces." << ::std::endl;

    os << std::endl
       << "\033[1m--lsg-port\033[0m \033[4mport\033[0m                 Listen for the lobby service gateway" << ::std::endl
       << "                                connections on \033[4mport\033[0m. The default is 3074. If" << ::std::endl
       << "                                \033[4mport\033[0m is 0, then the system chooses a free port" << ::std::endl
       << "                                (see \033[1m--print-endpoints\033[0m)." << ::std::endl;

    os << std::endl
       << "\033[1m--bandwidth-address\033[0m \033[4maddr\033[0m        Receive the bandwidth test packets on \033[4maddr\033[0m. The" << ::std::endl
       << "                                default is all IPv4 interfaces." << ::std::endl;

    os << std::endl
       << "\033[1m--bandwidth-port\033[0m \033[4mport\033[0m           Receive the bandwidth test packets on UDP \033[4mport\033[0m." << ::std::endl
       << "                                The default is 3075. If \033[4mport\033[0m is 0, then the" << ::std::endl
       << "                                system chooses a free port (see" << ::std::endl
       << "                                \033[1m--print-endpoints\033[0m)." << ::std::endl;

    os << std::endl
       << "\033[1m--bandwidth-public-address\033[0m \033[4maddr\033[0m The IPv4 address the clients send the bandwidth" << ::std::endl
       << "                                test packets to. If unspecified, it is the" << ::std::endl
       << "                                address the client reached the gateway at," << ::std::endl
       << "                                which is only right if the bandwidth test" << ::std::endl
       << "                                packets are received on that address too and" << ::std::endl
       << "                                the client can reach it directly (rather than" << ::std::endl
       << "                                through NAT or a proxy). Note that without an" << ::std::endl
       << "                                IPv4 address the clients cannot test their" << ::std::endl
       << "                                bandwidth, in which case they assume they have" << ::std::endl
       << "                                enough." << ::std::endl;

    os << std::endl
       << "\033[1m--bandwidth-public-port\033[0m \033[4mport\033[0m    The UDP port the clients send the bandwidth" << ::std::endl
       << "                                test packets to. If unspecified, it is the port" << ::std::endl
       << "                                they are received on (see \033[1m--bandwidth-port\033[0m)." << ::std::endl;

    os << std::endl
       << "\033[1m--tls-certificate\033[0m \033[4mfile\033[0m          The authentication server certificate chain in" << ::std::endl
       << "                                the PEM format. Required." << ::std::endl;

    os << std::endl
       << "\033[1m--tls-key\033[0m \033[4mfile\033[0m                  The authentication server private key in the" << ::std::endl
       << "                                PEM format. Required." << ::std::endl;

    os << std::endl
       << "\033[1m--ticket-key\033[0m \033[4mfile\033[0m               Read the server ticket sealing key (32 raw" << ::std::endl
       << "                                bytes) from \033[4mfile\033[0m. If unspecified, a random key" << ::std::endl
       << "                                is generated on startup, which means the" << ::std::endl
       << "                                tickets issued before a restart are no longer" << ::std::endl
       << "                                accepted (the clients authenticate again)." << ::std::endl;

    os << std::endl
       << "\033[1m--title\033[0m \033[4mid\033[0m                      Serve the title \033[4mid\033[0m. Repeat this option to serve" << ::std::endl
       << "                                several titles. If unspecified, any title is" << ::std::endl
       << "                                served." << ::std::endl;

    os << std::endl
       << "\033[1m--ticket-lifetime\033[0m \033[4msec\033[0m           The time the client has to connect to the" << ::std::endl
       << "                                gateway after authenticating. The default is" << ::std::endl
       << "                                3600 seconds." << ::std::endl;

    os << std::endl
       << "\033[1m--sandbox\033[0m \033[4mname\033[0m                  The sandbox name reported to the clients. The" << ::std::endl
       << "                                default is \033[1mRETAIL\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--platform\033[0m \033[4mname\033[0m                 The device platform info reported to the" << ::std::endl
       << "                                clients. The default is \033[1mPC\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--publisher-files\033[0m \033[4mdir\033[0m           Publish the files in the subdirectories of \033[4mdir\033[0m" << ::std::endl
       << "                                as the publisher files of the titles that the" << ::std::endl
       << "                                subdirectories are named after. The clients of" << ::std::endl
       << "                                the title can list and download these files," << ::std::endl
       << "                                for example, IW4x (title 2010) downloads its" << ::std::endl
       << "                                playlists from \033[1m2010/playlists.patch2\033[0m. The \033[1mobe\033[0m" << ::std::endl
       << "                                package installs the IW4x files into the" << ::std::endl
       << "                                \033[1mpublisher/\033[0m subdirectory of its data directory" << ::std::endl
       << "                                (for example, \033[1m/usr/share/obe/publisher/\033[0m)." << ::std::endl
       << ::std::endl
       << "                                The files are published on startup, replacing" << ::std::endl
       << "                                the contents of the publisher files with the" << ::std::endl
       << "                                same names. Note that a file that is removed" << ::std::endl
       << "                                from \033[4mdir\033[0m stays published." << ::std::endl;

    os << std::endl
       << "\033[1m--print-endpoints\033[0m               Print the authentication, gateway, and" << ::std::endl
       << "                                bandwidth test endpoints to \033[1mstdout\033[0m, one per" << ::std::endl
       << "                                line, once listening. This is primarily useful" << ::std::endl
       << "                                together with port 0, which makes the system" << ::std::endl
       << "                                choose a free port." << ::std::endl;

    os << std::endl
       << "\033[1m--db-name\033[0m \033[4mname\033[0m                  Keep the stored files and performance values in" << ::std::endl
       << "                                the PostgreSQL database \033[4mname\033[0m. If unspecified," << ::std::endl
       << "                                they are kept in memory and are lost on exit," << ::std::endl
       << "                                which is only suitable for development. The" << ::std::endl
       << "                                database schema must be created or migrated" << ::std::endl
       << "                                with \033[1m--migrate\033[0m beforehand." << ::std::endl;

    os << std::endl
       << "\033[1m--db-user\033[0m \033[4muser\033[0m                  The PostgreSQL database user. If unspecified," << ::std::endl
       << "                                the user name of the process is used." << ::std::endl;

    os << std::endl
       << "\033[1m--db-password\033[0m \033[4mpass\033[0m              The PostgreSQL database password. Note that the" << ::std::endl
       << "                                command line is visible to other users, so" << ::std::endl
       << "                                consider specifying it in an options file (see" << ::std::endl
       << "                                \033[1m--options-file\033[0m) or in the PostgreSQL password" << ::std::endl
       << "                                file (see the \033[1mPGPASSFILE\033[0m environment variable)." << ::std::endl
       << "                                If unspecified, no password is sent." << ::std::endl;

    os << std::endl
       << "\033[1m--db-host\033[0m \033[4mhost\033[0m                  The PostgreSQL database host name, address, or" << ::std::endl
       << "                                UNIX-domain socket directory. If unspecified," << ::std::endl
       << "                                the \033[1mPGHOST\033[0m environment variable is used and," << ::std::endl
       << "                                without it, the socket in \033[1m/tmp\033[0m. A local server" << ::std::endl
       << "                                normally has its socket elsewhere" << ::std::endl
       << "                                (\033[1m/var/run/postgresql\033[0m on Fedora and Debian), so" << ::std::endl
       << "                                it is reached with its socket directory, for" << ::std::endl
       << "                                example, \033[1m--db-host /var/run/postgresql\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--db-port\033[0m \033[4mport\033[0m                  The PostgreSQL database port. If unspecified," << ::std::endl
       << "                                the default port is used." << ::std::endl;

    os << std::endl
       << "\033[1m--db-max-connections\033[0m \033[4mnum\033[0m        The most concurrent PostgreSQL database" << ::std::endl
       << "                                connections, which is also the number of" << ::std::endl
       << "                                threads that perform the database operations." << ::std::endl
       << "                                The default is 5." << ::std::endl;

    os << std::endl
       << "\033[1m--db-retry\033[0m \033[4mnum\033[0m                  Retry a database operation that fails with a" << ::std::endl
       << "                                recoverable error (for example, a serialization" << ::std::endl
       << "                                failure due to a concurrent update or a lost" << ::std::endl
       << "                                connection) up to \033[4mnum\033[0m times. The default is 10." << ::std::endl;

    os << std::endl
       << "\033[1m--migrate\033[0m                       Create the PostgreSQL database schema if there" << ::std::endl
       << "                                is none or migrate it to the current version," << ::std::endl
       << "                                then exit. Several servers may share the" << ::std::endl
       << "                                database, in which case the schema should be" << ::std::endl
       << "                                migrated once, before starting the servers of" << ::std::endl
       << "                                the new version. Requires \033[1m--db-name\033[0m." << ::std::endl;

    os << std::endl
       << "\033[1m--insecure-authentication\033[0m       Accept any platform token without verifying it," << ::std::endl
       << "                                deriving the user identity from the token" << ::std::endl
       << "                                itself. Anyone presenting the same token is the" << ::std::endl
       << "                                same user, so this is only suitable for" << ::std::endl
       << "                                development." << ::std::endl;

    p = ::obe::cli::usage_para::option;

    return p;
  }

  typedef
  std::map<std::string, void (*) (options&, ::obe::cli::scanner&)>
  _cli_options_map;

  static _cli_options_map _cli_options_map_;

  struct _cli_options_map_init
  {
    _cli_options_map_init ()
    {
      _cli_options_map_["--help"] =
      &::obe::cli::thunk< options, &options::help_ >;
      _cli_options_map_["--version"] =
      &::obe::cli::thunk< options, &options::version_ >;
      _cli_options_map_["--options-file"] =
      &::obe::cli::thunk< options, std::string, &options::options_file_,
        &options::options_file_specified_ >;
      _cli_options_map_["-v"] =
      &::obe::cli::thunk< options, &options::v_ >;
      _cli_options_map_["-V"] =
      &::obe::cli::thunk< options, &options::V_ >;
      _cli_options_map_["--quiet"] =
      &::obe::cli::thunk< options, &options::quiet_ >;
      _cli_options_map_["-q"] =
      &::obe::cli::thunk< options, &options::quiet_ >;
      _cli_options_map_["--verbose"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::verbose_,
        &options::verbose_specified_ >;
      _cli_options_map_["--auth-address"] =
      &::obe::cli::thunk< options, std::string, &options::auth_address_,
        &options::auth_address_specified_ >;
      _cli_options_map_["--auth-port"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::auth_port_,
        &options::auth_port_specified_ >;
      _cli_options_map_["--lsg-address"] =
      &::obe::cli::thunk< options, std::string, &options::lsg_address_,
        &options::lsg_address_specified_ >;
      _cli_options_map_["--lsg-port"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::lsg_port_,
        &options::lsg_port_specified_ >;
      _cli_options_map_["--bandwidth-address"] =
      &::obe::cli::thunk< options, std::string, &options::bandwidth_address_,
        &options::bandwidth_address_specified_ >;
      _cli_options_map_["--bandwidth-port"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::bandwidth_port_,
        &options::bandwidth_port_specified_ >;
      _cli_options_map_["--bandwidth-public-address"] =
      &::obe::cli::thunk< options, std::string, &options::bandwidth_public_address_,
        &options::bandwidth_public_address_specified_ >;
      _cli_options_map_["--bandwidth-public-port"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::bandwidth_public_port_,
        &options::bandwidth_public_port_specified_ >;
      _cli_options_map_["--tls-certificate"] =
      &::obe::cli::thunk< options, std::string, &options::tls_certificate_,
        &options::tls_certificate_specified_ >;
      _cli_options_map_["--tls-key"] =
      &::obe::cli::thunk< options, std::string, &options::tls_key_,
        &options::tls_key_specified_ >;
      _cli_options_map_["--ticket-key"] =
      &::obe::cli::thunk< options, std::string, &options::ticket_key_,
        &options::ticket_key_specified_ >;
      _cli_options_map_["--title"] =
      &::obe::cli::thunk< options, std::vector<std::uint32_t>, &options::title_,
        &options::title_specified_ >;
      _cli_options_map_["--ticket-lifetime"] =
      &::obe::cli::thunk< options, std::uint32_t, &options::ticket_lifetime_,
        &options::ticket_lifetime_specified_ >;
      _cli_options_map_["--sandbox"] =
      &::obe::cli::thunk< options, std::string, &options::sandbox_,
        &options::sandbox_specified_ >;
      _cli_options_map_["--platform"] =
      &::obe::cli::thunk< options, std::string, &options::platform_,
        &options::platform_specified_ >;
      _cli_options_map_["--publisher-files"] =
      &::obe::cli::thunk< options, std::string, &options::publisher_files_,
        &options::publisher_files_specified_ >;
      _cli_options_map_["--print-endpoints"] =
      &::obe::cli::thunk< options, &options::print_endpoints_ >;
      _cli_options_map_["--db-name"] =
      &::obe::cli::thunk< options, std::string, &options::db_name_,
        &options::db_name_specified_ >;
      _cli_options_map_["--db-user"] =
      &::obe::cli::thunk< options, std::string, &options::db_user_,
        &options::db_user_specified_ >;
      _cli_options_map_["--db-password"] =
      &::obe::cli::thunk< options, std::string, &options::db_password_,
        &options::db_password_specified_ >;
      _cli_options_map_["--db-host"] =
      &::obe::cli::thunk< options, std::string, &options::db_host_,
        &options::db_host_specified_ >;
      _cli_options_map_["--db-port"] =
      &::obe::cli::thunk< options, std::uint16_t, &options::db_port_,
        &options::db_port_specified_ >;
      _cli_options_map_["--db-max-connections"] =
      &::obe::cli::thunk< options, std::size_t, &options::db_max_connections_,
        &options::db_max_connections_specified_ >;
      _cli_options_map_["--db-retry"] =
      &::obe::cli::thunk< options, std::size_t, &options::db_retry_,
        &options::db_retry_specified_ >;
      _cli_options_map_["--migrate"] =
      &::obe::cli::thunk< options, &options::migrate_ >;
      _cli_options_map_["--insecure-authentication"] =
      &::obe::cli::thunk< options, &options::insecure_authentication_ >;
    }
  };

  static _cli_options_map_init _cli_options_map_init_;

  bool options::
  _parse (const char* o, ::obe::cli::scanner& s)
  {
    _cli_options_map::const_iterator i (_cli_options_map_.find (o));

    if (i != _cli_options_map_.end ())
    {
      (*(i->second)) (*this, s);
      return true;
    }

    return false;
  }

  bool options::
  _parse (::obe::cli::scanner& s,
          ::obe::cli::unknown_mode opt_mode,
          ::obe::cli::unknown_mode arg_mode)
  {
    // Can't skip combined flags (--no-combined-flags).
    //
    assert (opt_mode != ::obe::cli::unknown_mode::skip);

    bool r = false;
    bool opt = true;

    while (s.more ())
    {
      const char* o = s.peek ();

      if (std::strcmp (o, "--") == 0)
      {
        opt = false;
        s.skip ();
        r = true;
        continue;
      }

      if (opt)
      {
        if (_parse (o, s))
        {
          r = true;
          continue;
        }

        if (std::strncmp (o, "-", 1) == 0 && o[1] != '\0')
        {
          // Handle combined option values.
          //
          std::string co;
          if (const char* v = std::strchr (o, '='))
          {
            co.assign (o, 0, v - o);
            ++v;

            int ac (2);
            char* av[] =
            {
              const_cast<char*> (co.c_str ()),
              const_cast<char*> (v)
            };

            ::obe::cli::argv_scanner ns (0, ac, av);

            if (_parse (co.c_str (), ns))
            {
              // Parsed the option but not its value?
              //
              if (ns.end () != 2)
                throw ::obe::cli::invalid_value (co, v);

              s.next ();
              r = true;
              continue;
            }
            else
            {
              // Set the unknown option and fall through.
              //
              o = co.c_str ();
            }
          }

          // Handle combined flags.
          //
          char cf[3];
          {
            const char* p = o + 1;
            for (; *p != '\0'; ++p)
            {
              if (!((*p >= 'a' && *p <= 'z') ||
                    (*p >= 'A' && *p <= 'Z') ||
                    (*p >= '0' && *p <= '9')))
                break;
            }

            if (*p == '\0')
            {
              for (p = o + 1; *p != '\0'; ++p)
              {
                std::strcpy (cf, "-");
                cf[1] = *p;
                cf[2] = '\0';

                int ac (1);
                char* av[] =
                {
                  cf
                };

                ::obe::cli::argv_scanner ns (0, ac, av);

                if (!_parse (cf, ns))
                  break;
              }

              if (*p == '\0')
              {
                // All handled.
                //
                s.next ();
                r = true;
                continue;
              }
              else
              {
                // Set the unknown option and fall through.
                //
                o = cf;
              }
            }
          }

          switch (opt_mode)
          {
            case ::obe::cli::unknown_mode::skip:
            {
              s.skip ();
              r = true;
              continue;
            }
            case ::obe::cli::unknown_mode::stop:
            {
              break;
            }
            case ::obe::cli::unknown_mode::fail:
            {
              throw ::obe::cli::unknown_option (o);
            }
          }

          break;
        }
      }

      switch (arg_mode)
      {
        case ::obe::cli::unknown_mode::skip:
        {
          s.skip ();
          r = true;
          continue;
        }
        case ::obe::cli::unknown_mode::stop:
        {
          break;
        }
        case ::obe::cli::unknown_mode::fail:
        {
          throw ::obe::cli::unknown_argument (o);
        }
      }

      break;
    }

    return r;
  }
}

namespace obe
{
  ::obe::cli::usage_para
  print_obe_usage (::std::ostream& os, ::obe::cli::usage_para p)
  {
    CLI_POTENTIALLY_UNUSED (os);

    if (p != ::obe::cli::usage_para::none)
      os << ::std::endl;

    os << "\033[1mSYNOPSIS\033[0m" << ::std::endl
       << ::std::endl
       << "\033[1mobe\033[0m [\033[4moptions\033[0m]\033[0m" << ::std::endl
       << ::std::endl
       << "\033[1mDESCRIPTION\033[0m" << ::std::endl
       << ::std::endl
       << "\033[1mobe\033[0m serves Demonware online services that IW4x connects to: the authentication" << ::std::endl
       << "over HTTPS, the lobby service gateway over TCP, and the bandwidth test over" << ::std::endl
       << "UDP. It runs until interrupted (\033[1mSIGINT\033[0m or \033[1mSIGTERM\033[0m)." << ::std::endl
       << ::std::endl
       << "The authentication accepts the Xbox Live style platform tokens that IW4x" << ::std::endl
       << "issues. Each IW4x installation signs its tokens with its own key and the user" << ::std::endl
       << "id (XUID) is derived from that key, so a user id can only be presented with its" << ::std::endl
       << "key. See \033[1m--insecure-authentication\033[0m for development." << ::std::endl;

    p = ::obe::options::print_usage (os, ::obe::cli::usage_para::text);

    return p;
  }
}

// Begin epilogue.
//
//
// End epilogue.

