# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

import libs = libobe-apache%lib{obe-apache}

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript{**}
