// Copyright (c) the IW4x authors (see the AUTHORS file).
// SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

#pragma once

#include <map>

#include <libobe/types.hxx>
#include <libobe/utility.hxx>

#include <libobe/service.hxx>

#include <libobe/export.hxx>

namespace obe
{
  // The matchmaking session id (XNKID) and key exchange key (XNKEY), both
  // generated by us when the session is created.
  //
  using session_id = array<uint8_t, 8>;
  using exchange_key = array<uint8_t, 16>;

  // The matchmaking session information (bdMatchMakingInfo and the title's
  // derived class), as registered by the host and returned by the search:
  //
  // blob[37]  host address            (bdCommonAddr, opaque to us)
  // blob[8]   session id
  // blob[16]  key exchange key
  // int32     available public slots
  // int32     occupied public slots
  // int32     available private slots
  // int32     occupied private slots
  // int32...  title attributes        (see the search queries)
  //
  // Note that the client stores the slot counts as bytes.
  //
  struct LIBOBE_SYMEXPORT session_info
  {
    static constexpr size_t address_size = 37;

    // The title attributes we accept (the title has 9).
    //
    static constexpr size_t max_attributes = 32;

    array<uint8_t, address_size> address {};
    session_id                   id {};
    exchange_key                 key {};
    int32_t                      available_public = 0;
    int32_t                      occupied_public = 0;
    int32_t                      available_private = 0;
    int32_t                      occupied_private = 0;
    vector<int32_t>              attributes;

    session_info () = default;

    // Parse the information, taking the int32 values that follow the slot
    // counts as the attributes. Throw bit_parsing on failure.
    //
    explicit
    session_info (bit_parser&);

    void
    serialize (bit_serializer&) const;
  };

  struct matchmaking_settings
  {
    // The most sessions returned by a search (the client stores 50).
    //
    size_t max_results = 50;

    // The most sessions a connection can host at a time.
    //
    size_t max_hosted = 4;
  };

  // The matchmaking service (bdMatchMaking, service 5).
  //
  // All the requests start with a uchar8 0 (presumably reserved). The
  // operations are:
  //
  // 1 create  The session information (with the id and key ignored)
  //           followed by two raw zero bytes. Reply with uint32 1 (the
  //           result count) and the generated id and key as blobs.
  //
  // 2 modify  As above but with the id of the session to modify. No
  //           results.
  //
  // 3 delete  The id as a blob. No results.
  //
  // 5 search  The int32 query id, int32 maximum result count, and the
  //           int32 query parameters, followed by two raw zero bytes. Reply
  //           with uint32 count and the information of that many sessions
  //           of the title.
  //
  // The sessions live as long as the connection that created them: the
  // client deletes its session when it stops hosting, but if it goes away
  // without doing so, we drop the session when its connection closes.
  //
  // The search queries are the title's (on the original server they are
  // defined per title), so we implement the ones this title uses (see
  // service-matchmaking.cxx for details). Note that the client doesn't check
  // the sessions it gets other than skipping its own: it lists and probes
  // them all, so the search must only return the sessions it can join.
  //
  class LIBOBE_SYMEXPORT matchmaking_service: public service
  {
  public:
    explicit
    matchmaking_service (matchmaking_settings = {});

    virtual kind_type
    kind () const noexcept override {return kind_type::bit;}

    virtual awaitable<void>
    handle (const lsg_identity&,
            uint8_t operation,
            bit_parser&,
            bit_serializer&) override;

    virtual void
    disconnect (const lsg_identity&) noexcept override;

  private:
    struct session
    {
      title_id     title;
      user_id      owner;
      uint64_t     connection;
      session_info info;
    };

    // Find the session and verify that the client may change it. Throw
    // task_error otherwise.
    //
    std::map<session_id, session>::iterator
    find (const lsg_identity&, const session_id&);

    void
    create (const lsg_identity&, bit_parser&, bit_serializer&);

    void
    modify (const lsg_identity&, bit_parser&);

    void
    remove (const lsg_identity&, bit_parser&);

    void
    search (const lsg_identity&, bit_parser&, bit_serializer&);

  private:
    const matchmaking_settings    settings_;
    std::map<session_id, session> sessions_;
  };
}
