# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{obe-apache}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBOBE_APACHE_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBOBE_APACHE_SHARED_BUILD

# Export options.
#
lib{obe-apache}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{obe-apache}: cxx.export.poptions += -DLIBOBE_APACHE_STATIC
libs{obe-apache}: cxx.export.poptions += -DLIBOBE_APACHE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{obe-apache}: bin.lib.version = "-$version.project_id"
else
  lib{obe-apache}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libobe/apache/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libobe/apache/
  install.subdirs = true
}
