# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

import libs = libobe%lib{obe}

./: exe{driver}: {hxx ixx txx cxx}{**} $libs testscript

# The test-only private key (the testscript passes its path to the driver).
#
./: file{key.pem}
